// import "./globals.css";
// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";
// import Head from "next/head";
// export const metadata = {
//   title: "Law Firm",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <Head>
//           {/* Adding a CDN link for a CSS file */}

//           <link
//             rel="stylesheet"
//             href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
//             integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
//             crossorigin="anonymous"
//           ></link>
//         </Head>
//         {children}
//       </body>
//     </html>
//   );
// }
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export const metadata = {
  title: "Law Firm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Adding Bootstrap */}
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
          crossOrigin="anonymous"
        />

        {/* Adding the chatbot script */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.chtlConfig = { chatbotId: "2342537174" };
            `,
          }}
        />
        <script
          async
          data-id="2342537174"
          id="chatling-embed-script"
          type="text/javascript"
          src="https://chatling.ai/js/embed.js"
        ></script>
      </head>
      <body>{children}</body>
    </html>
  );
}
